open Alcotest
module Private_key = Bondi_client.Private_key

(* --- The committed keys ---

   fixtures/*.key were generated once with [ssh-keygen] and [openssl] and
   committed, rather than produced by the test run. Generating them per run
   would make every case assert whatever the local tool chain defaults to
   today, which is the opposite of what these cases are for: the contract names
   [aes256-ctr] as the cipher an encrypted OpenSSH key reports, and a fixture
   regenerated by a future OpenSSH that defaults to something else must fail
   here rather than quietly re-agree with itself.

   No key in them is authorised anywhere. Each holds the passphrase
   [fixture-passphrase] where it holds one, which is stated here because it is
   not a secret and a reader who cannot tell is left guessing. *)

let fixture name =
  let path = Filename.concat "fixtures" name in
  let channel = open_in_bin path in
  Fun.protect
    ~finally:(fun () -> close_in_noerr channel)
    (fun () -> really_input_string channel (in_channel_length channel))

let pp_encryption formatter = function
  | Private_key.Unencrypted -> Format.pp_print_string formatter "Unencrypted"
  | Private_key.Encrypted { cipher } ->
      Format.fprintf formatter "Encrypted { cipher = %S }" cipher

let equal_encryption left right =
  match (left, right) with
  | Private_key.Unencrypted, Private_key.Unencrypted -> true
  | Private_key.Encrypted left, Private_key.Encrypted right ->
      String.equal left.cipher right.cipher
  | (Private_key.Unencrypted | Private_key.Encrypted _), _ -> false

let pp_unreadable formatter = function
  | Private_key.No_armour -> Format.pp_print_string formatter "No_armour"
  | Private_key.Body_not_base64 ->
      Format.pp_print_string formatter "Body_not_base64"
  | Private_key.Body_not_openssh found ->
      Format.fprintf formatter "Body_not_openssh %S" found

let equal_unreadable left right =
  match (left, right) with
  | Private_key.No_armour, Private_key.No_armour -> true
  | Private_key.Body_not_base64, Private_key.Body_not_base64 -> true
  | Private_key.Body_not_openssh left, Private_key.Body_not_openssh right ->
      String.equal left right
  | ( ( Private_key.No_armour | Private_key.Body_not_base64
      | Private_key.Body_not_openssh _ ),
      _ ) ->
      false

(* Hand-written rather than derived: a printer generated over these types would
   also be generated over whatever they come to carry, and the sibling types
   this feature adds carry a passphrase. *)
let classification =
  result
    (testable pp_encryption equal_encryption)
    (testable pp_unreadable equal_unreadable)

let unencrypted_is_unencrypted () =
  check classification "an unencrypted openssh key needs no passphrase"
    (Ok Private_key.Unencrypted)
    (Private_key.encryption (fixture "openssh_unencrypted.key"))

let encrypted_names_its_cipher () =
  check classification "the cipher name is read from the key body"
    (Ok (Private_key.Encrypted { cipher = "aes256-ctr" }))
    (Private_key.encryption (fixture "openssh_aes256_ctr.key"))

(* The manifest carries a key either base64-wrapped or verbatim and announces
   neither, so the wrapped form must reach the same verdict as the form it
   wraps. Asserting both the literal and the agreement: the literal alone would
   pass an implementation that classified every wrapped key as encrypted, and
   the agreement alone would pass one that read neither. *)
let base64_wrapped_classifies_as_its_decoded_self () =
  let wrapped =
    Private_key.encryption (fixture "openssh_aes256_ctr_base64.key")
  in
  check classification "a wrapped key reaches its own verdict"
    (Ok (Private_key.Encrypted { cipher = "aes256-ctr" }))
    wrapped;
  check classification "and the same verdict as the key it wraps"
    (Private_key.encryption (fixture "openssh_aes256_ctr.key"))
    wrapped

(* Neither container states its cipher anywhere a reader that does not parse
   DER can reach, so each answers its container's name. What must not happen is
   that either reads as unencrypted: that is the verdict that stages a key
   which cannot sign and reports the failure as the host's. *)
let pem_containers_are_encrypted () =
  check classification "a traditional PEM key is encrypted"
    (Ok (Private_key.Encrypted { cipher = "pem" }))
    (Private_key.encryption (fixture "legacy_pem_encrypted.key"));
  check classification "a pkcs8 key is encrypted"
    (Ok (Private_key.Encrypted { cipher = "pkcs8" }))
    (Private_key.encryption (fixture "pkcs8_encrypted.key"))

(* A body too short to hold the magic must not be mistaken for a key whose
   cipher field said [none]. The payload is the bytes found in the magic's
   place, which is what makes the rejection readable without the fixture. *)
let truncated_body_is_unreadable () =
  check classification "a truncated body is not a classification"
    (Error (Private_key.Body_not_openssh "openss"))
    (Private_key.encryption (fixture "openssh_truncated.key"))

(* The two arms the classifier can reach before it has read anything at all.
   Neither is a failure of the key: [No_armour] is a value that is not a PEM
   container -- a public key pasted in place of a private one reaches it -- and
   [Body_not_base64] is a container whose body was elided or mangled between
   the markers. They are pinned here because this module is the only place they
   are produced, and an arm produced nowhere in a suite is an arm whose
   collapse at the call site nothing notices. *)
let unarmoured_value_has_no_armour () =
  check classification "a value with no BEGIN line is not a PEM container"
    (Error Private_key.No_armour)
    (Private_key.encryption (fixture "no_armour.key"))

let armoured_body_that_is_not_base64 () =
  check classification "armour around a body that is not base64 says so"
    (Error Private_key.Body_not_base64)
    (Private_key.encryption (fixture "armoured_body_not_base64.key"))

(* --- The resolution ---

   A passphrase is abstract, so an expectation cannot be written as a literal
   and equality cannot read the representation. Both go through
   [expose_to_askpass], the one way out, which is also the whole point of the
   type: a test that wanted to print one would have to name the extractor, and
   so would a line of production code that leaked it. The printer below
   deliberately does not, even for a failure report. *)
let pp_refusal formatter = function
  | Private_key.Encrypted_without_passphrase { cipher } ->
      Format.fprintf formatter "Encrypted_without_passphrase { cipher = %S }"
        cipher
  | Private_key.Unreadable_body { detail } ->
      Format.fprintf formatter "Unreadable_body { detail = %S }" detail

let equal_refusal left right =
  match (left, right) with
  | ( Private_key.Encrypted_without_passphrase left,
      Private_key.Encrypted_without_passphrase right ) ->
      String.equal left.cipher right.cipher
  | Private_key.Unreadable_body left, Private_key.Unreadable_body right ->
      String.equal left.detail right.detail
  | ( ( Private_key.Encrypted_without_passphrase _
      | Private_key.Unreadable_body _ ),
      _ ) ->
      false

let pp_identity formatter = function
  | Private_key.Ambient -> Format.pp_print_string formatter "Ambient"
  | Private_key.Staged_key -> Format.pp_print_string formatter "Staged_key"
  | Private_key.Own_agent _ ->
      Format.pp_print_string formatter "Own_agent { passphrase = <withheld> }"
  | Private_key.Refused { reason } ->
      Format.fprintf formatter "Refused { reason = %a }" pp_refusal reason

let equal_identity left right =
  match (left, right) with
  | Private_key.Ambient, Private_key.Ambient -> true
  | Private_key.Staged_key, Private_key.Staged_key -> true
  | Private_key.Own_agent left, Private_key.Own_agent right ->
      String.equal
        (Private_key.expose_to_askpass left.passphrase)
        (Private_key.expose_to_askpass right.passphrase)
  | Private_key.Refused left, Private_key.Refused right ->
      equal_refusal left.reason right.reason
  | ( ( Private_key.Ambient | Private_key.Staged_key | Private_key.Own_agent _
      | Private_key.Refused _ ),
      _ ) ->
      false

let resolution = testable pp_identity equal_identity

(* The passphrase a fixture key was made with. Not a secret: it unlocks a key
   authorised nowhere, and a reader who cannot tell which string this is is
   left guessing at the two cases that turn on it. *)
let fixture_passphrase = "fixture-passphrase"

(* A manifest may decline to carry key material at all, which is how an
   operator uses the agent, [~/.ssh/config] or hardware key they already hold.
   A passphrase with no key to unlock is not a key either -- there is nothing
   for it to open -- so both shapes reach the same outcome. *)
let no_key_resolves_to_ambient () =
  check resolution "no key at all leaves ssh to its own configuration"
    Private_key.Ambient
    (Private_key.identity ~contents:None ~passphrase:None);
  check resolution
    "and a passphrase with nothing to unlock does not change that"
    Private_key.Ambient
    (Private_key.identity ~contents:None ~passphrase:(Some fixture_passphrase))

(* Today's behaviour, and it must survive. The second assertion is the one that
   catches a resolution keyed on whether a passphrase was supplied rather than
   on whether the key needs one: an unencrypted key is staged either way. *)
let unencrypted_key_resolves_to_staged () =
  check resolution "an unencrypted key is written out and handed to ssh"
    Private_key.Staged_key
    (Private_key.identity
       ~contents:(Some (fixture "openssh_unencrypted.key"))
       ~passphrase:None);
  check resolution "and a passphrase it does not need is ignored"
    Private_key.Staged_key
    (Private_key.identity
       ~contents:(Some (fixture "openssh_unencrypted.key"))
       ~passphrase:(Some fixture_passphrase))

(* The case the feature exists for. The passphrase must arrive at the agent
   intact -- an outcome that merely said "use an agent" would authenticate no
   better than today. *)
let encrypted_key_with_a_passphrase_resolves_to_its_own_agent () =
  let resolved =
    Private_key.identity
      ~contents:(Some (fixture "openssh_aes256_ctr.key"))
      ~passphrase:(Some fixture_passphrase)
  in
  match resolved with
  | Private_key.Own_agent { passphrase } ->
      check string "the agent is given the passphrase the manifest carried"
        fixture_passphrase
        (Private_key.expose_to_askpass passphrase)
  | Private_key.Ambient
  | Private_key.Staged_key
  | Private_key.Refused _ ->
      failf "expected an agent of its own, got %a" pp_identity resolved

(* Refused rather than staged: a key that cannot sign is offered, accepted and
   then fails as the host's authorization error, which is the defect this
   closes. The cipher is carried out of the classifier so the refusal can name
   it. *)
let encrypted_key_without_a_passphrase_is_refused () =
  check resolution "an encrypted key with no passphrase cannot work"
    (Private_key.Refused
       {
         reason =
           Private_key.Encrypted_without_passphrase { cipher = "aes256-ctr" };
       })
    (Private_key.identity
       ~contents:(Some (fixture "openssh_aes256_ctr.key"))
       ~passphrase:None);
  check resolution "and a container key is refused by its container's name"
    (Private_key.Refused
       { reason = Private_key.Encrypted_without_passphrase { cipher = "pem" } })
    (Private_key.identity
       ~contents:(Some (fixture "legacy_pem_encrypted.key"))
       ~passphrase:None)

(* The authority on whether a key is usable is ssh, not this parser, and a
   value carrying no armour at all is a format this parser has not met: staged
   exactly as today, with or without a passphrase. Refusing it would turn every
   container this parser does not read into a deploy bondi declines and ssh
   would have accepted. *)
let unarmoured_key_is_staged_not_refused () =
  check resolution "a value this parser cannot recognise is still handed to ssh"
    Private_key.Staged_key
    (Private_key.identity
       ~contents:(Some (fixture "no_armour.key"))
       ~passphrase:None);
  check resolution "and a passphrase alongside it does not make it an agent's"
    Private_key.Staged_key
    (Private_key.identity
       ~contents:(Some (fixture "no_armour.key"))
       ~passphrase:(Some fixture_passphrase))

(* Armour and then a body that is not one. This is not a format the parser has
   not met -- the value named its own container and did not hold one -- so it is
   refused rather than staged, which is the whole of the difference from the
   case above. A passphrase does not rescue it either: there is nothing here for
   an agent to be given. *)
let armoured_key_with_an_unreadable_body_is_refused () =
  check resolution "a body that is not base64 is refused, not staged"
    (Private_key.Refused
       {
         reason =
           Private_key.Unreadable_body
             { detail = "the body between the armour markers is not base64" };
       })
    (Private_key.identity
       ~contents:(Some (fixture "armoured_body_not_base64.key"))
       ~passphrase:None);
  check resolution "a body too short to hold the magic is refused, not staged"
    (Private_key.Refused
       {
         reason =
           Private_key.Unreadable_body
             {
               detail =
                 "the body decoded and did not begin with the OpenSSH key \
                  magic; found \"openss\"";
             };
       })
    (Private_key.identity
       ~contents:(Some (fixture "openssh_truncated.key"))
       ~passphrase:(Some fixture_passphrase))

(* The shape the incident arrives in. A multi-line key substituted into a
   double-quoted YAML scalar is flow-folded: every newline becomes a space, the
   armour and the body run together on one line, and every line the reader then
   sees begins with the armour dashes -- so the body it recovers is empty and
   the key is no longer a key.

   Staged, this is offered to the host, accepted, and then fails to sign, and
   the operator reads "Permission denied (publickey)" for a fault that happened
   before anything was dialled. The passphrase is supplied here on purpose: the
   folded key is the encrypted one, and an implementation that refused only when
   no passphrase was given would let exactly this case through. *)
let a_folded_key_is_refused () =
  check resolution "a key folded onto one line is refused before anything runs"
    (Private_key.Refused
       {
         reason =
           Private_key.Unreadable_body
             {
               detail =
                 "the body decoded and did not begin with the OpenSSH key \
                  magic; found \"\"";
             };
       })
    (Private_key.identity
       ~contents:(Some (fixture "openssh_aes256_ctr_folded.key"))
       ~passphrase:(Some fixture_passphrase))

(* Every manifest in the estate declares the passphrase field and almost all
   leave it empty, so the empty string is the common case rather than an edge.
   It is not a passphrase: the constructor answers [None], which is what makes
   an agent with nothing to unlock with unrepresentable rather than merely
   untested. *)
let empty_passphrase_is_not_a_passphrase () =
  check (option string) "the empty string builds no passphrase" None
    (Option.map Private_key.expose_to_askpass (Private_key.passphrase ""));
  check (option string) "a real one builds one that keeps its value"
    (Some fixture_passphrase)
    (Option.map Private_key.expose_to_askpass
       (Private_key.passphrase fixture_passphrase));
  check resolution "so an encrypted key with an empty passphrase is refused"
    (Private_key.Refused
       {
         reason =
           Private_key.Encrypted_without_passphrase { cipher = "aes256-ctr" };
       })
    (Private_key.identity
       ~contents:(Some (fixture "openssh_aes256_ctr.key"))
       ~passphrase:(Some ""))

(* The sentence an operator reads. It names the server, the field and the
   cipher, because the failure it replaces named none of them and read as the
   host's verdict; and it names the second legal shape, because "supply a
   passphrase" is not the only remedy and an operator who wanted their own
   agent should be told so. The absence arm is checked on the same call that
   the arm above pins in full, so a message gone empty cannot pass it. *)
let refusal_names_server_field_and_cipher () =
  let message =
    Private_key.refusal_message ~server:"1.2.3.4"
      ~reason:
        (Private_key.Encrypted_without_passphrase { cipher = "aes256-ctr" })
  in
  check string "the refusal says what is wrong and what may be done about it"
    "server 1.2.3.4: the private key in ssh.private_key_contents is encrypted \
     (aes256-ctr) and ssh.private_key_pass is empty; set the passphrase, or \
     remove the key and let ssh use your own configuration"
    message;
  check bool "and it carries no passphrase" false
    (Bondi_common.String_utils.contains ~needle:fixture_passphrase message)

(* The other refusal. It has a different remedy to name -- nothing is wrong with
   the passphrase and setting one would not help -- so it names the two
   encodings that survive substitution, because the value that reaches here was
   usually a key that was intact when it was exported. *)
let unreadable_refusal_names_the_reason_and_the_encodings () =
  let message =
    Private_key.refusal_message ~server:"1.2.3.4"
      ~reason:
        (Private_key.Unreadable_body
           { detail = "the body between the armour markers is not base64" })
  in
  check string "the refusal says what could not be read and what to do instead"
    "server 1.2.3.4: the private key in ssh.private_key_contents has PEM \
     armour around a body this client cannot read -- the body between the \
     armour markers is not base64; a key substituted into a quoted scalar is \
     folded onto one line and stops being a key, so carry it base64-encoded or \
     as a block scalar, or remove the key and let ssh use your own \
     configuration"
    message

let () =
  run "Private_key"
    [
      ( "classifying a key",
        [
          test_case "an unencrypted openssh key is read as unencrypted" `Quick
            unencrypted_is_unencrypted;
          test_case "an aes256-ctr key names its cipher" `Quick
            encrypted_names_its_cipher;
          test_case "a base64-wrapped key classifies as its decoded self" `Quick
            base64_wrapped_classifies_as_its_decoded_self;
          test_case "a legacy PEM and a pkcs8 key are read as encrypted" `Quick
            pem_containers_are_encrypted;
          test_case "a truncated body is unreadable rather than unencrypted"
            `Quick truncated_body_is_unreadable;
          test_case "a value with no armour is unreadable as such" `Quick
            unarmoured_value_has_no_armour;
          test_case "armour around a non-base64 body is unreadable as such"
            `Quick armoured_body_that_is_not_base64;
        ] );
      ( "resolving an identity",
        [
          test_case "no key resolves to ambient" `Quick
            no_key_resolves_to_ambient;
          test_case "an unencrypted key resolves to staged" `Quick
            unencrypted_key_resolves_to_staged;
          test_case
            "an encrypted key with a passphrase resolves to its own agent"
            `Quick encrypted_key_with_a_passphrase_resolves_to_its_own_agent;
          test_case "an encrypted key without a passphrase is refused" `Quick
            encrypted_key_without_a_passphrase_is_refused;
          test_case "a key with no armour is staged, not refused" `Quick
            unarmoured_key_is_staged_not_refused;
          test_case "armour around an unreadable body is refused, not staged"
            `Quick armoured_key_with_an_unreadable_body_is_refused;
          test_case "a key folded onto one line is refused" `Quick
            a_folded_key_is_refused;
          test_case "an empty passphrase is not a passphrase" `Quick
            empty_passphrase_is_not_a_passphrase;
          test_case
            "the refusal names server, field and cipher and never the \
             passphrase"
            `Quick refusal_names_server_field_and_cipher;
          test_case "an unreadable body is refused in its own words" `Quick
            unreadable_refusal_names_the_reason_and_the_encodings;
        ] );
    ]
