(include_subdirs qualified)

(library
 (name bondi_server)
 (public_name bondi.server)
 (libraries
  bondi.common
  eio
  eio_main
  cohttp
  cohttp-eio
  tls-eio
  tls
  ca-certs
  mirage-crypto-rng.unix
  domain-name
  base64
  yojson
  uri
  unix
  cmdliner
  ppx_deriving.show
  ppx_deriving_yojson)
 (preprocess
  (pps ppx_deriving.eq ppx_deriving.show ppx_deriving_yojson)))
