name: push-docker-image
description: Push Docker image to Gitlab Registry

inputs:
  username:
    description: The username to login to the Gitlab registry
    required: true
  password:
    description: The password to login to the Gitlab registry
    required: true
  version:
    description: The version of the image to push
    required: true

runs:
  using: "composite"

  steps:
    - name: Login to GitLab
      uses: docker/login-action@v3
      with:
        registry: registry.gitlab.com
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Docker push image
      run: |
        docker push registry.gitlab.com/puravida.software/grokkr-go:${{ inputs.version }}
      shell: bash
